margin = 80
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
long_to_short_function_def = true
separate_kwargs_with_semicolon = true

verbose = true

